#!/bin/sh
if ! head -1 "$1" | grep -qE "^(feat|fix|chore|docs|test|style|refactor|perf|build|ci|revert)(\(.+?\))?: .{1,}$"; then
    echo "\033[0;31mAborting commit. Your commit message is invalid.\033[0m" >&2
    exit 1
fi
if ! head -1 "$1" | grep -qE "^.{1,88}$"; then
    echo "\033[0;31mAborting commit. Your commit message is too long.\033[0m" >&2
    exit 1
fi
